#!/bin/bash
 
# xpl: 打开指定路径的文件管理器，缺省是当前目录

cygwin=false;
case "`uname`" in
    CYGWIN*) cygwin=true ;;
esac
 
if [ "$1" = "" ]; then
    XPATH=. # 缺省是当前目录
else
    XPATH=$1
    if $cygwin; then
        XPATH="$(cygpath -C ANSI -w "$XPATH")";
    fi
fi
 
explorer '/select,' $XPATH
